# fly.toml app configuration file generated for elixir-phoenix-discuss on 2024-02-26T01:31:15-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elixir-phoenix-discuss'
primary_region = 'jnb'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'elixir-phoenix-discuss.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
